project_id = "brncdfacgdcctcfqaufh"

[functions.analyze-semantic]
verify_jwt = false

[functions.generate-summary]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false
